#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- /sbin/su-exec ${GEARMAN_USER}:${GEARMAN_GROUP} /usr/sbin/gearmand --log-file stderr "$@"
fi

exec "$@"
